version: "3.7"

services:

   pokerocket_endpoints:
      build: ./docker/python3
      container_name: pokerocket_endpoints
      env_file:
         - ${HOME}/.pokerocket/pokerocket_db.env
      environment:
         - FLASK_APP=/mnt/host/pokerocket_endpoints/run.py
         - MYSQL_HOST=pokerocket_db
         - MYSQL_PORT=3306
      networks:
         rocketnet:
      expose: #Expose ports without publishing them to the host machine - they’ll only be accessible to containers on the same network.
         - "5000"
      ports: # Publish to host os
         - "5000:5000"
      depends_on:
         - pokerocket_db
      volumes:
         - ./pokerocket_endpoints:/mnt/host/pokerocket_endpoints
      command: bash /mnt/host/pokerocket_endpoints/entrypoint.sh


   pokerocket_db:
      image: mysql:8.0.21
      container_name: pokerocket_db
      env_file:
         - ${HOME}/.pokerocket/pokerocket_db.env
      networks:
         rocketnet:
      environment:
         - MYSQL_DATABASE=pokerocketdb
      volumes:
         - ./pokerocket_db:/mnt/host/pokerocket_db
      command: --default-authentication-plugin=mysql_native_password
      restart: always


   pokerocket_adminer:
      container_name: pokerocket_adminer
      image: adminer
      restart: always
      depends_on:
         - pokerocket_db
      networks:
         rocketnet:
      ports:
         - 8080:8080


   pokerocket_automation:
      build: ./docker/openjdk11
      container_name: pokerocket_automation
      environment:
         - POKEROCKET_ENDPOINTS=pokerocket_endpoints
      networks:
         rocketnet:
      depends_on:
         - pokerocket_endpoints
      expose: #Expose ports without publishing them to the host machine - they’ll only be accessible to containers on the same network.
         - "8080"
      ports: # Publish to host os
         - "8081:8080"
      volumes:
         - ./pokerocket_automation:/mnt/host/pokerocket_automation
         - ${HOME}/.m2:/root/.m2
      command: bash /mnt/host/pokerocket_automation/entrypoint.sh


networks:
   rocketnet:
